spring:
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: "*"

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: create
    database: h2
    open-in-view: false
    show-sql: true

logging:
  level:
    root: info